"""Pick the best seed from a training campaign and record the outcome.

Re-scores every candidate through the grading path rather than trusting the return
logged during training, then runs the checks a local ``try_agent.py`` cannot catch: that
the pickle resolves through ``agent_interface`` alone, and that it holds no CUDA
storages.

``--install`` writes ``models/model.obj``, the graded filename.

Usage::

    pixi run python residual_sac/select_best.py --runs runs --install
"""

import argparse
import glob
import json
import os
import subprocess
import sys
from datetime import date

import numpy as np

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

from agent_interface import convert_action, convert_obs  # noqa: E402
from util import create_env, load_model, save_model  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS_PATH = os.path.join(HERE, 'RESULTS.md')
MODEL_PATH = os.path.join(REPO_ROOT, 'models', 'model.obj')


def grader_score(model, episodes=3, seed=42):
    """
    :return: mean episodic return through the harness loop
    """
    env = create_env(seed=seed, render_env=False, limit_speed_factor=None,
                     render_width=1280)
    returns = []
    for i in range(episodes):
        obs, _ = env.reset(seed=seed + i)
        total, done = 0.0, False
        while not done:
            obs, reward, terminated, truncated, _ = env.step(
                convert_action(model.get_action(convert_obs(obs))))
            total += reward
            done = terminated or truncated
        returns.append(total)
    env.close()
    return float(np.mean(returns))


def check_cpu_only(model):
    """
    :return: (ok, offending tensor name or None)
    """
    for name, tensor in list(model.named_parameters()) + list(model.named_buffers()):
        if tensor.device.type != 'cpu':
            return False, name
    for name, tensor in getattr(model, 'actor_state', {}).items():
        if tensor.device.type != 'cpu':
            return False, f'actor_state.{name}'
    return True, None


def check_pickle_module(path):
    """
    :return: (ok, qualified class name or error message)
    """
    code = ("import pickle, sys;"
            f"sys.path.insert(0, {REPO_ROOT!r});"
            f"m = pickle.load(open({path!r}, 'rb'));"
            "print(type(m).__module__ + '.' + type(m).__name__)")
    proc = subprocess.run([sys.executable, '-c', code], cwd='/', capture_output=True,
                          text=True)
    if proc.returncode != 0:
        return False, proc.stderr.strip().splitlines()[-1]
    name = proc.stdout.strip()
    return name.startswith('agent_interface.'), name


def write_results(rows, winner, score, pickle_msg, cpu_ok, episodes):
    """Write RESULTS.md as tables of measured values."""
    seeds = '\n'.join(f"| `{os.path.basename(os.path.dirname(p))}` | {s:.5f} |"
                      for s, p in rows)
    summary = os.path.join(os.path.dirname(winner), 'summary.json')
    trained = ''
    if os.path.exists(summary):
        with open(summary) as fh:
            meta = json.load(fh)
        trained = (f"| Baseline (zero residual) | {meta['baseline']:.5f} |\n"
                   f"| Best during training | {meta['best_return']:.5f} |\n"
                   f"| Timesteps | {meta['total_timesteps']} |\n"
                   f"| Wall clock | {meta['wall_seconds'] / 3600:.2f} h |\n")

    text = f"""# Residual SAC - results

Generated by `residual_sac/select_best.py` on {date.today().isoformat()}.

## Best agent

| Metric | Value |
| --- | --- |
| **Mean return** | **{score:.5f}** |
| Episodes | {episodes} |
| Seed | `{os.path.basename(os.path.dirname(winner))}` |

## Winning run

| Metric | Value |
| --- | --- |
{trained}
## All seeds

| Seed | Mean return |
| --- | --- |
{seeds}

## Checks

| Check | Result |
| --- | --- |
| Foreign-cwd unpickle | {pickle_msg} |
| CPU-only tensors | {'pass' if cpu_ok else 'FAIL'} |
| Artifact | `models/model.obj` |
"""
    with open(RESULTS_PATH, 'w') as fh:
        fh.write(text)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--runs', default=os.path.join(REPO_ROOT, 'runs'))
    parser.add_argument('--episodes', type=int, default=3)
    parser.add_argument('--install', action='store_true',
                        help='write models/model.obj')
    args = parser.parse_args()

    candidates = sorted(glob.glob(os.path.join(args.runs, '*', 'best.obj')))
    if not candidates:
        sys.exit(f"no checkpoints under {args.runs}")

    rows = []
    for path in candidates:
        model = load_model(path).to('cpu')
        score = grader_score(model, args.episodes)
        cpu_ok, offender = check_cpu_only(model)
        rows.append((score, path))
        print(f"{score:9.4f}  {os.path.relpath(path, REPO_ROOT)}"
              f"{'' if cpu_ok else f'  [NOT ON CPU: {offender}]'}")

    rows.sort(reverse=True, key=lambda r: r[0])
    score, winner = rows[0]
    print(f"\nbest: {winner}  ({score:.4f})")

    if not args.install:
        return

    save_model(load_model(winner).to('cpu'), MODEL_PATH)
    installed = load_model(MODEL_PATH)
    pickle_ok, pickle_msg = check_pickle_module(MODEL_PATH)
    cpu_ok, offender = check_cpu_only(installed)
    print(f"pickle module check: {'OK' if pickle_ok else 'FAILED'} ({pickle_msg})")
    print(f"cpu-only check: {'OK' if cpu_ok else f'FAILED ({offender})'}")
    if not (pickle_ok and cpu_ok):
        sys.exit("refusing to leave a broken model in place")

    write_results(rows, winner, grader_score(installed, args.episodes), pickle_msg,
                  cpu_ok, args.episodes)
    print(f"wrote {RESULTS_PATH}")


if __name__ == '__main__':
    main()
